import { DIDURLListener } from './DIDURLListener';
import { ParserRuleContext } from "antlr4ts/ParserRuleContext";
import { TerminalNode } from "antlr4ts/tree/TerminalNode";
import { ErrorNode } from "antlr4ts/tree/ErrorNode";
import { DIDURLParser } from './DIDURLParser';

export class DIDURLBaseListener implements DIDURLListener {
	public enterDidurl(ctx: DIDURLParser.DidurlContext): void { }
	public exitDidurl(ctx: DIDURLParser.DidurlContext): void { }
	public enterDid(ctx: DIDURLParser.DidContext): void { }
	public exitDid(ctx: DIDURLParser.DidContext): void { }
	public enterMethod(ctx: DIDURLParser.MethodContext): void { }
	public exitMethod(ctx: DIDURLParser.MethodContext): void { }
	public enterMethodSpecificString(ctx: DIDURLParser.MethodSpecificStringContext): void { }
	public exitMethodSpecificString(ctx: DIDURLParser.MethodSpecificStringContext): void { }
	public enterParams(ctx: DIDURLParser.ParamsContext): void { }
	public exitParams(ctx: DIDURLParser.ParamsContext): void { }
	public enterParam(ctx: DIDURLParser.ParamContext): void { }
	public exitParam(ctx: DIDURLParser.ParamContext): void { }
	public enterParamQName(ctx: DIDURLParser.ParamQNameContext): void { }
	public exitParamQName(ctx: DIDURLParser.ParamQNameContext): void { }
	public enterParamMethod(ctx: DIDURLParser.ParamMethodContext): void { }
	public exitParamMethod(ctx: DIDURLParser.ParamMethodContext): void { }
	public enterParamName(ctx: DIDURLParser.ParamNameContext): void { }
	public exitParamName(ctx: DIDURLParser.ParamNameContext): void { }
	public enterParamValue(ctx: DIDURLParser.ParamValueContext): void { }
	public exitParamValue(ctx: DIDURLParser.ParamValueContext): void { }
	public enterPath(ctx: DIDURLParser.PathContext): void { }
	public exitPath(ctx: DIDURLParser.PathContext): void { }
	public enterQuery(ctx: DIDURLParser.QueryContext): void { }
	public exitQuery(ctx: DIDURLParser.QueryContext): void { }
	public enterQueryParam(ctx: DIDURLParser.QueryParamContext): void { }
	public exitQueryParam(ctx: DIDURLParser.QueryParamContext): void { }
	public enterQueryParamName(ctx: DIDURLParser.QueryParamNameContext): void { }
	public exitQueryParamName(ctx: DIDURLParser.QueryParamNameContext): void { }
	public enterQueryParamValue(ctx: DIDURLParser.QueryParamValueContext): void { }
	public exitQueryParamValue(ctx: DIDURLParser.QueryParamValueContext): void { }
	public enterFrag(ctx: DIDURLParser.FragContext): void { }
	public exitFrag(ctx: DIDURLParser.FragContext): void { }
	public enterEveryRule(ctx: ParserRuleContext): void { }
	public exitEveryRule(ctx: ParserRuleContext): void { }
	public visitTerminal(node: TerminalNode): void { }
	public visitErrorNode(node: ErrorNode): void { }
}